import Head from "next/head";
import Card from "../components/Card";

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Divi-CRM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="text-4xl">Divi-CRM</nav>
      <main>
        <Card />
      </main>
    </div>
  );
}
